# Generated by Django 2.2.7 on 2019-11-19 03:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('joined_date', models.DateField(auto_now_add=True)),
                ('registration_date', models.DateField(blank=True, null=True)),
                ('name', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('is_guest', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('action_id', models.PositiveSmallIntegerField()),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Task')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.User')),
            ],
        ),
    ]
